2025-01-29 10:34:03,531 INFO    MainThread:206578 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /home/erkan/Desktop/PhD/projects/associative_classification/wandb/run-20250129_103403-zl4pwfqc/logs/debug.log
2025-01-29 10:34:03,531 INFO    MainThread:206578 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /home/erkan/Desktop/PhD/projects/associative_classification/wandb/run-20250129_103403-zl4pwfqc/logs/debug-internal.log
2025-01-29 10:34:03,531 INFO    MainThread:206578 [wandb_init.py:init():756] calling init triggers
2025-01-29 10:34:03,531 INFO    MainThread:206578 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'batch_size': 64, 'epochs': 2, '_wandb': {}}
2025-01-29 10:34:03,531 INFO    MainThread:206578 [wandb_init.py:init():789] starting backend
2025-01-29 10:34:03,531 INFO    MainThread:206578 [wandb_init.py:init():793] sending inform_init request
2025-01-29 10:34:03,532 INFO    MainThread:206578 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-29 10:34:03,532 INFO    MainThread:206578 [wandb_init.py:init():808] backend started and connected
2025-01-29 10:34:03,533 INFO    MainThread:206578 [wandb_init.py:init():901] updated telemetry
2025-01-29 10:34:03,534 INFO    MainThread:206578 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-01-29 10:34:03,909 INFO    MainThread:206578 [wandb_init.py:init():984] starting run threads in backend
2025-01-29 10:34:04,157 INFO    MainThread:206578 [wandb_run.py:_console_start():2385] atexit reg
2025-01-29 10:34:04,158 INFO    MainThread:206578 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-01-29 10:34:04,159 INFO    MainThread:206578 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-01-29 10:34:04,160 INFO    MainThread:206578 [wandb_run.py:_redirect():2325] Redirects installed.
2025-01-29 10:34:04,164 INFO    MainThread:206578 [wandb_init.py:init():1026] run started, returning control to user process
2025-01-29 10:34:05,049 WARNING MsgRouterThr:206578 [router.py:message_loop():75] message_loop has been closed
